-- Deprecated.
-- The backend schema and seed data are now managed by Flyway migrations under:
-- backend/src/main/resources/db/migration
--
-- Docker Compose no longer mounts this directory into MySQL. Keep this file only
-- as a marker so older deployment notes do not accidentally run the pre-Flyway
-- initialization script.
